version: '2.4'
services:
  web:
    image: nfqlt/nginx118
    ports:
      - '10.24.97.33:80:80'
    links:
      - fastcgi
    volumes:
      - './src:/home/project/src'
      - './conf.d/nginx.conf:/etc/nginx/sites-enabled/default:ro'
    environment:
      NFQ_DOCUMENT_ROOT: /home/project/src
      NFQ_PROJECT_ROOT: /home/project/src


  dev:
    image: nfqlt/php74-dev
    ports:
      - '10.24.97.33:22:22'
    links:
      - mysql
    volumes:
      - './src:/home/project/src'
      - '/home/project/.ssh:/home/project/.ssh'
      - '/etc/ssh:/etc/ssh'
      - '/etc/gitconfig:/etc/gitconfig'
      - '/etc/environment:/etc/environment-vm:ro'
      - '../../tools/env-projects:/etc/environment-projects'
      - '/vagrant/bash_custom:/home/project/.bash_custom'
    environment:
      NFQ_ENABLE_PHP_MODULES: 'bcmath opcache gd mysqlnd pdo pdo_mysql exif intl zip sockets json curl ctype iconv tokenizer mbstring xml dom simplexml'
      NFQ_PROJECT_ROOT: /home/project/src
      NFQ_PROJECT_GIT_REPO: 'git@gitlab.com:nfq-technologies/delta/atlantic-express-car-market/car-marketplace-client.git'
      NFQ_PROJECT_GIT_BRANCH: develop
      NFQ_INIT_SCRIPT: tools/docker/develop_init.sh


  fastcgi:
    image: nfqlt/php74-fpm
    links:
      - mysql
    volumes:
      - './src:/home/project/src'
      - './conf.d/custom_php_dev_fpm.ini:/etc/php/7.4/fpm/conf.d/90-custom.ini:ro'
    environment:
      NFQ_PROJECT_ROOT: /home/project/src
      NFQ_ENABLE_PHP_MODULES: 'bcmath opcache gd mysqlnd pdo pdo_mysql exif intl zip sockets json curl ctype iconv tokenizer mbstring xml dom simplexml'


  mysql:
    image: nfqlt/mysql80
    ports:
      - '10.24.97.33:3306:3306'
    volumes_from:
      - 'service:mysqlVol:rw'


  mysqlVol:
    image: nfqlt/mysql80-data
    volumes:
      - /var/lib/mysql


volumes: {  }
networks:
  default:
    ipam:
      config:
        -
          subnet: 10.24.97.33/28
